#!/bin/bash
set -euo pipefail

: "${REPO_URL:?REPO_URL is required}"
: "${BRANCH:?BRANCH is required}"
: "${BASE_BRANCH:?BASE_BRANCH is required}"
: "${TASK_PROMPT:?TASK_PROMPT is required}"
: "${OPENAI_API_BASE:?OPENAI_API_BASE is required}"
: "${AIDER_MODEL:?AIDER_MODEL is required}"
: "${GH_TOKEN:?GH_TOKEN is required}"
: "${CALLBACK_URL:?CALLBACK_URL is required}"
: "${TASK_ID:?TASK_ID is required}"

WORKSPACE="/workspace"
STATUS="completed"
PR_URL=""

json_escape() {
    python -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
}

send_callback() {
    local pr_json="null"
    local run_json="null"
    if [ -n "${PR_URL}" ]; then
        pr_json=$(printf "%s" "${PR_URL}" | json_escape)
    fi
    if [ -n "${RUN_ID:-}" ]; then
        run_json=$(printf "%s" "${RUN_ID}" | json_escape)
    fi

    curl -s -X POST "${CALLBACK_URL}" \
        -H "Content-Type: application/json" \
        -d "{\"task_id\":\"${TASK_ID}\",\"run_id\":${run_json},\"status\":\"${STATUS}\",\"pr_url\":${pr_json}}" \
        || echo "WARNING: Failed to send callback"
}

cleanup() {
    local exit_status=$?
    if [ "${exit_status}" -ne 0 ]; then
        STATUS="failed"
    fi
    send_callback
    exit "${exit_status}"
}
trap cleanup EXIT

echo "=== Agent starting ==="
echo "Repo: ${REPO_URL}"
echo "Branch: ${BRANCH}"
echo "Base: ${BASE_BRANCH}"
echo "Model: ${AIDER_MODEL}"

echo "--- Cloning repository ---"
git clone "${REPO_URL}" "${WORKSPACE}"
cd "${WORKSPACE}"

git config user.email "agent@orchestrator.local"
git config user.name "AI Agent"

echo "--- Creating branch ${BRANCH} from ${BASE_BRANCH} ---"
git checkout "${BASE_BRANCH}" 2>/dev/null || git checkout -b "${BASE_BRANCH}" "origin/${BASE_BRANCH}"
git checkout -b "${BRANCH}"

echo "--- Running Aider ---"
aider \
    --message "${TASK_PROMPT}" \
    --model "${AIDER_MODEL}" \
    --auto-commits \
    --yes-always \
    --no-auto-lint \
    --no-suggest-shell-commands \
    --no-show-model-warnings

echo "--- Pushing branch ---"
git push -u origin "${BRANCH}"

echo "--- Creating PR ---"
PR_URL=$(gh pr create \
    --title "agent: ${BRANCH}" \
    --body "Automated implementation by AI Agent.

Task: ${TASK_PROMPT:0:500}

---
Generated by AI Agent Orchestrator" \
    --base "${BASE_BRANCH}" \
    --head "${BRANCH}")

echo "PR created: ${PR_URL}"
echo "=== Agent completed ==="
